repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
{{ if eq (env "SUPERSET") "YES" }}
- name: superset
  namespace: default
  chart: stable/superset
{{ end }}

